### ISSUE TITLE
canopen DBUS scan error on rpi

### ISSUE THREAD

**Issue by jaghatei** [ConnectorIO/connectorio-addons#1]
On start of first OH thing using canopen addon this error occurs on debian on raspberry pi as the required NetworkManager is not present in this environment.

```
[ERROR] [DBusCANInterfaceDiscoveryService] - Discovery of can interfaces via dbus failed org.freedesktop.dbus.errors.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
```

**Comment by splatch** [comment]
This issue will be handled independently through network interface discovery which was introduced as a part of work involving fatek binding.

Please note that error indicates that communication with DBus daemon failed, however it does not prevent binding from working. It just marks failure of automatic can interface discovery.
