### ISSUE TITLE
canopen.ta CAN input channel not created if unit is automatic

### ISSUE THREAD

**Issue by jaghatei** [ConnectorIO/connectorio-addons#2]
Issue opened to document the current way of handling units by the binding:

In case the CAN input is set to automatic the following error prevents the channel creation in case the unit of the CAN input is set to automatic on TA hardware.

```
[INFO ] [DefaultChannelFactory] - Ignoring analog I/O object TAAnalogInput[1] unit=-1, name=TACanString(CAN AI 1) [220f, 0], configuredUnit=-1 object. **Could not find matching channel and thing for unit -1**
```

Currently only workaround is to set a specific unit type for CAN input in TA hardware.

**Comment by splatch** [comment]
There were some improvements related to that, the `-1` value is a placeholder for automatic unit handling based on received values. Please re-open your report if issue remains.
