### ISSUE TITLE
Iconify support for openHAB 4

### ISSUE THREAD

**Issue by ThaDaVos** [ConnectorIO/connectorio-addons#21]
Add support for Openhab 4 - specifically `org.connectorio.addons.ui.iconify`

**Comment by splatch** [comment]
Hello @ThaDaVos, somehow github didn't notify me about this issue. I am working on updates of remaining changes for 3.0-3.4 versions and as soon as these are completed I will start working on 4.x line of addons.

**Comment by ThaDaVos** [comment]
Hearing that often - probably a bug in Github then (having the same issues myself)

Thanks for the update!

**Comment by splatch** [comment]
Iconify icon provider is updated to v4 APIs https://community.openhab.org/t/iconify-icon-provider-4-0-0-0-5-0-0-0/149990. It still uses old syntax for iconsets. Would you be interested in having separate iconsets for each subset of icons?

**Comment by rliegmann** [comment]
I get the following error while installing:
`2023-10-03 11:56:17.746 [ERROR] [org.apache.felix.fileinstall        ] - Failed to install artifact: /openhab/addons/org.connectorio.addons.ui.iconify-4.0.0-20230928.jar
java.io.IOException: Resetting to invalid mark
	at java.io.BufferedInputStream.reset(BufferedInputStream.java:446) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.installOrUpdateBundle(DirectoryWatcher.java:1034) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:963) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:884) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:489) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) ~[?:?]`

I use openHAB version:   4.0.0.M2

Maybe the error is already known?
Thank you.

**Comment by splatch** [comment]
This is low level error which is unrelated to addon, but seem to be related to copy process/processing of addons. From path it looks to be a docker deployment. Can you share more details when/how it happens? Do you install addon manually through addons folder or through marketplace client in OH?

**Comment by rliegmann** [comment]
Yes, it is a Docker environment.
I tried to install the addon from the addon folder. Honestly, I forgot that you can also install the addons via the marketplace. I've done this now and it's worked without any problems so far.
That's how it works for now.
But thanks for the super quick answer :-)

**Comment by splatch** [comment]
Closing issue as completed. There are no more troubles to cover.
Just in case - most recent builds can be fetched through https://repository.connectorio.cloud/.
