### ISSUE TITLE
Support wireless m-bus for openHAB 4.0.3

### ISSUE THREAD

**Issue by JensHoRi** [ConnectorIO/connectorio-addons#27]
Happy to get feedback if someone else uses 4.0.3 and wmbus :-)

**Comment by JensHoRi** [comment]
Not sure what you mean... I didn't found a binding named nexus. I still have 4.0.0.pr-31-SNAPSHOT of wmbus binding installed

**Comment by splatch** [comment]
Its there, the #31 was created as a temporary solution to test #29 made for master, but on top of OH 4.0.x APIs. The #29 is merged and included and master and 4.0.x branch was already rebased several times.

Could you please look at version: https://repository.connectorio.cloud/#browse/browse:co7io-public-snapshots:org%2Fconnectorio%2Faddons%2Forg.connectorio.addons.kar.wmbus%2F4.0.0-SNAPSHOT ? Latest version is `4.0.0-20240305.174310-8`, in case if next snapshot is being made version can be interpreted as `4.0.0-<date>.<time>-<number>`.
There is also corresponding build for OH 4.1.x.

**Comment by JensHoRi** [comment]
I installed Version org.connectorio.addons.kar.wmbus-4.1.0-20240305.150633-5.kar

- Stick / Bridge up and running
- Cold Water meter online and running, receiving data on all channels
- Hot water meter online and running, receiving data on all channels
- Techem Heat Meter thing is online BUT with only one channel rssi (no rssi data, no further channels within 1 hour)
- Techem Hot Water Heating meter (unencrypted) shows error:

`HANDLER_CONFIGURATION_PENDING
{deviceType=Der Wert RESERVED ist nicht in den erlaubten Optionen enthalten. Erlaubte Optionen sind: [ParameterOption [value="OTHER", label="OTHER"], ParameterOption [value="OIL_METER", label="OIL_METER"], ParameterOption [value="ELECTRICITY_METER", label="ELECTRICITY_METER"], ParameterOption [value="GAS_METER", label="GAS_METER"], ParameterOption [value="HEAT_METER", label="HEAT_METER"], ParameterOption [value="STEAM_METER", label="STEAM_METER"], ParameterOption [value="WARM_WATER_METER", label="WARM_WATER_METER"], ParameterOption [value="WATER_METER", label="WATER_METER"], ParameterOption [value="HEAT_COST_ALLOCATOR", label="HEAT_COST_ALLOCATOR"], ParameterOption [value="COMPRESSED_AIR", label="COMPRESSED_AIR"], ParameterOption [value="COOLING_METER_OUTLET", label="COOLING_METER_OUTLET"], ParameterOption [value="COOLING_METER_INLET", label="COOLING_METER_INLET"], ParameterOption [value="HEAT_METER_INLET", label="HEAT_METER_INLET"], ParameterOption [value="HEAT_COOLING_METER", label="HEAT_COOLING_METER"], ParameterOption [value="BUS_SYSTEM_COMPONENT", label="BUS_SYSTEM_COMPONENT"], ParameterOption [value="UNKNOWN", label="UNKNOWN"], ParameterOption [value="CALORIFIC_VALUE", label="CALORIFIC_VALUE"], ParameterOption [value="HOT_WATER_METER", label="HOT_WATER_METER"], ParameterOption [value="COLD_WATER_METER", label="COLD_WATER_METER"], ParameterOption [value="DUAL_REGISTER_WATER_METER", label="DUAL_REGISTER_WATER_METER"], ParameterOption [value="PRESSURE_METER", label="PRESSURE_METER"], ParameterOption [value="AD_CONVERTER", label="AD_CONVERTER"], ParameterOption [value="SMOKE_DETECTOR", label="SMOKE_DETECTOR"], ParameterOption [value="ROOM_SENSOR_TEMP_HUM", label="ROOM_SENSOR_TEMP_HUM"], ParameterOption [value="GAS_DETECTOR", label="GAS_DETECTOR"], ParameterOption [value="BREAKER_ELEC", label="BREAKER_ELEC"], ParameterOption [value="VALVE_GAS_OR_WATER", label="VALVE_GAS_OR_WATER"], ParameterOption [value="CUSTOMER_UNIT_DISPLAY_DEVICE", label="CUSTOMER_UNIT_DISPLAY_DEVICE"], ParameterOption [value="WASTE_WATER_METER", label="WASTE_WATER_METER"], ParameterOption [value="GARBAGE", label="GARBAGE"], ParameterOption [value="COM_CONTROLLER", label="COM_CONTROLLER"], ParameterOption [value="UNIDIRECTION_REPEATER", label="UNIDIRECTION_REPEATER"], ParameterOption [value="BIDIRECTION_REPEATER", label="BIDIRECTION_REPEATER"], ParameterOption [value="RADIO_CONVERTER_SYSTEM_SIDE", label="RADIO_CONVERTER_SYSTEM_SIDE"], ParameterOption [value="RADIO_CONVERTER_METER_SIDE", label="RADIO_CONVERTER_METER_SIDE"]]} `

So in general from last try to today: Techem don't show decryption error anymore, but still didn't work. Warm Water Heating Kamstrup Techem unencrypted now with error (earlier expected keys, now this looks like solved but not recognized as correct device)

Does this test help?

**Comment by splatch** [comment]
Thank you Jens, this helps. Message you got comes from invalid configuration generated by discovery phase, your techem devices report themselves (at the protocol level) as `reserved` instead of any of types which are supported.
I'll add a fix to exclude reserved devices from results, simply because they can't be handled without further addons/configurations/mappings.
As for Kamstrup device - I have access to two flow iq. I hope to give it a try and see what goes on with their data.

**Comment by splatch** [comment]
I am closing this issue as all builds for OH 4.0.x-4.2.x are now being published by CI/CD pipeline. Binaries can be obtained from nexus at https://repository.connectorio.cloud.
Other points mentioned in this report deserve separate feature requests, as they touch specifics of wmbus device/frame mapping. For techem devices there are two issues: #43 and #46.
