### ISSUE TITLE
ta_device reload config does not change channels

### ISSUE THREAD

**Issue by jaghatei** [ConnectorIO/connectorio-addons#3]
I replaced the program on the TA hardware by a new one with different CAN inputs and outputs.
The binding reloaded data from the TA hardware after "reload" was set, but did not create new / changed channel objects.

Removing binding and recreating it new did the job and instanced all CAN inputs and outputs .

**Comment by splatch** [comment]
Earlier versions of TA binding had troubles with access to acquire all necessary data from controller. This area received some updates which should stabilize functionality. Please re-open issue if issue remains.
