### ISSUE TITLE
canopen.ta: Values transmitted on canbus are not stable

### ISSUE THREAD

**Issue by jaghatei** [ConnectorIO/connectorio-addons#4]
Although value in OH is not changed the value transported on canbus is instable.
Example:
(2021-08-18 10:15:46.506018)  can0  202   [8]  **B2** 00 00 00 00 00 00 00
(2021-08-18 10:15:56.574312)  can0  202   [8]  **00** 00 00 00 00 00 00 00
(2021-08-18 10:16:46.534185)  can0  202   [8]  **B2** 00 00 00 00 00 00 00

Sending the "00" value seems to happen exactly 10 seconds after real value is sent consequently nullifying all awaited values at destination nodes.

**Comment by jaghatei** [comment]
A fresh OH installation with canopen.ta binding solved the issue. Now the correct value is sent once each minute as it should.
 
But this means that there must have been artifacts in OH sending the "00" value to either of these steps I did during testing:
a) changing node id of brigde from 1 to 2
b) setting canopen.ta thing to "reload" to refresh channels from device (which does not work #3)
c) deleting canopen.ta thing and reacreating it to have clean channel mappings for inputs and outputs.
d) bind / unbind / create / delete items connected to the affrected can input

**Comment by splatch** [comment]
Given that there is no reproduction criteria lets close this one. Feel free to re-open this issue if reproduction criteria is known.
