### ISSUE TITLE
Devices shown online in openhab while linked bridge (serial-jrxtx) is offline with error could not open port

### ISSUE THREAD

**Issue by JensHoRi** [ConnectorIO/connectorio-addons#44]
If the bridge is offline, the devices should show bridge not available instead of being online

**Comment by JensHoRi** [comment]
Just to let you know: At least if bridge is deactivated devices are correct shown as offline Bridge / Handler offline.

**Comment by splatch** [comment]
Thank you for confirmation. I'll then make this issue as resolved.
