### ISSUE TITLE
Support bacnet for openHAB 4.0.x

### ISSUE THREAD

**Issue by MarkusThur** [ConnectorIO/connectorio-addons#48]
Dear Splash, as "wished",

opening a ticket  for BACnet support in OH4.. Thnik it makes sense to start with the newes stable version of OH

**Comment by splatch** [comment]
Please give a try to this build: https://repository.connectorio.cloud/#browse/browse:co7io-public-snapshots:org%2Fconnectorio%2Faddons%2Forg.connectorio.addons.kar.bacnet%2F4.0.0- SNAPSHOT%2F4.0.0-20231106.121241-2 (download KAR and give it a run)

The 4.0 build is already there, there just no proper distribution method.

**Comment by splatch** [comment]
@MarkusThur Are you ok with above way? I plan to make a release of all stuff, however I need a bit of time to prepare entire pipeline for that.

To understand file names assigned by nexus check this section of docs: https://docs.connectorio.com/connectorio-addons/3.0.x/Installation.html#testing-development-snapshots

**Comment by splatch** [comment]
@MarkusThur I'm closing issue since I received no feedback for past few months. Please re-open issue if you consider it still valid.
