### ISSUE TITLE
Compiling for OH4

### ISSUE THREAD

**Issue by cdjackson** [ConnectorIO/connectorio-addons#90]
Hey @splatch - as discussed elsewhere, I've pulled the `4.1.x` branch, but it doesn't build -:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.connectorio:addons:4.1.0-SNAPSHOT: The following artifacts could not be resolved: org.connectorio:connectorio-oss:pom:5-SNAPSHOT (absent): org.connectorio:connectorio-oss:pom:5-SNAPSHOT was not found in https://repo1.maven.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 23, column 11
```

I've tried the `-Popenhab,thing4` option but this didn't help....

Thanks.

**Comment by splatch** [comment]
Ok, turns out that might be some leftover, the connectorio-oss 5 is already released to maven central. You can switch to it, it will work with maven central alone.

**Comment by cdjackson** [comment]
Thanks - that solves the parent pom issue, and compiling runs ok with the profiles you mentioned earlier. It fails in the itests, but that's ok for me as I can now just compile the one binding ok...

**Comment by splatch** [comment]
I've updated parent to released version, hence master branch and all other branches should build just fine.
@cdjackson Please re-open if issue still remains.

**Comment by cdjackson** [comment]
Thanks Łukasz - this is indeed working for me - thanks.
